apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: YOUR_DOCKER_USERNAME/api
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'screener'
            - name: MONGO_URI
              value: 'mongodb://api-mongo-srv:27017/screener'
            - name: GOOGLE_CLIENT_ID
              value: fill_it
            - name: GOOGLE_CLIENT_SECRET
              value: fill_it
            - name: COOKIE_KEY
              value: 'any'
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000