apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: YOUR_DOCKER_USERNAME/server
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.name'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'screener'
            - name: CLOUDINARY_CLOUD_NAME
              value: fill_it
            - name: CLOUDINARY_API_KEY
              value: fill_it
            - name: CLOUDINARY_API_SECRET
              value: fill_it